"use client";

import { useMemo, useState } from "react";
import { AppShell } from "../components/app-shell";
import { ProtectedPage } from "../components/protected-page";
import { DiscoveryImage } from "../components/discovery-image";
import { useAuth } from "../components/auth-provider";
import { useCommunity } from "../components/community-provider";
import { useDiscoveries } from "../components/discovery-provider";
import { AppLink as Link } from "../components/app-link";

export default function CommunityPage() {
  const { user } = useAuth(); const { records } = useDiscoveries(); const { posts, isReady, visitorKey, createPost, toggleLike, addComment, deletePost, deleteComment } = useCommunity();
  const [writeOpen, setWriteOpen] = useState(false); const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [discoveryId, setDiscoveryId] = useState(""); const [category, setCategory] = useState<"discovery" | "knowhow" | "safety">("discovery"); const [commentDrafts, setCommentDrafts] = useState<Record<string, string>>({});
  const publicRecords = useMemo(() => records.filter((record) => record.visibility === "public"), [records]);
  const submitPost = (event: React.FormEvent) => { event.preventDefault(); if (!user || !title.trim() || !content.trim()) return; const linked = publicRecords.find((record) => record.id === discoveryId); createPost({ title: title.trim(), content: content.trim(), category, discoveryId: linked?.id, speciesName: linked?.speciesName, speciesImageLabel: linked?.imageLabel, speciesImageTone: linked?.imageTone, locationName: linked?.locationName }, user.nickname); setTitle(""); setContent(""); setDiscoveryId(""); setCategory("discovery"); setWriteOpen(false); };
  const sendComment = (postId: string) => { if (!user) return; addComment(postId, user.nickname, commentDrafts[postId] ?? ""); setCommentDrafts((current) => ({ ...current, [postId]: "" })); };
  return <ProtectedPage><AppShell><section className="community-page">
    <header className="community-header"><div><p className="eyebrow">BUSAN SEA COMMUNITY</p><h1>부산 바다 이야기</h1><p>발견한 생물과 채집·관찰 노하우를 안전하게 나눠 보세요.</p></div><div className="community-actions"><Link className="outline-action" href="/ranking">⌁ 탐험가 랭킹</Link><button className="primary-action" onClick={() => setWriteOpen((open) => !open)}>{writeOpen ? "작성 닫기" : "＋ 이야기 공유하기"}</button></div></header>
    <section className="community-howto"><div><span>⌁</span><div><p className="eyebrow">FIELD NOTES</p><h2>채집보다 관찰을 먼저</h2><p>장갑, 미끄럼 방지 신발, 조수 시간 확인처럼 현장에서 도움이 된 노하우를 공유해 주세요.</p></div></div><button className="text-button" onClick={() => { setCategory("knowhow"); setWriteOpen(true); }}>노하우 작성하기 →</button></section>
    <p className="community-device-note">ⓘ 연결 키가 설정되면 모든 사용자의 게시물을 함께 표시합니다. 설정 전에는 이 기기의 발표용 데이터가 표시됩니다.</p>
    {writeOpen && <form className="community-composer" onSubmit={submitPost}><label>공유 종류 <select value={category} onChange={(event) => setCategory(event.target.value as "discovery" | "knowhow" | "safety")}><option value="discovery">발견 공유</option><option value="knowhow">채집·관찰 노하우</option><option value="safety">안전 수칙</option></select></label><label>제목<input value={title} onChange={(event) => setTitle(event.target.value)} maxLength={70} placeholder={category === "knowhow" ? "예: 간조 시간에 갯벌을 걷는 방법" : "예: 청사포에서 만난 말미잘"} required /></label><label>발견 기록 연결 <select value={discoveryId} onChange={(event) => setDiscoveryId(event.target.value)}><option value="">연결하지 않음</option>{publicRecords.map((record) => <option key={record.id} value={record.id}>{record.speciesName} · {record.locationName}</option>)}</select></label><label>내용<textarea value={content} onChange={(event) => setContent(event.target.value)} maxLength={500} placeholder="관찰한 특징, 준비물, 안전 수칙을 함께 나눠 주세요." required /></label><div><button className="outline-action" type="button" onClick={() => setWriteOpen(false)}>취소</button><button className="primary-action" type="submit">게시하기</button></div></form>}
    {!isReady ? <section className="empty-state"><b>⌁</b><h2>커뮤니티를 불러오는 중이에요</h2></section> : <section className="community-feed">{posts.map((post) => { const liked = Boolean(visitorKey && post.likes.includes(visitorKey)); const isMine = Boolean(visitorKey && post.authorKey === visitorKey); const categoryLabel = post.category === "knowhow" ? "채집·관찰 노하우" : post.category === "safety" ? "안전 수칙" : "발견 공유"; return <article className="community-post" key={post.id}><header><div className="community-avatar">{post.author.slice(0, 1)}</div><div><strong>{post.author}</strong><span>{new Date(post.createdAt).toLocaleString("ko-KR")}</span></div>{isMine && <button className="post-delete" onClick={() => { if (window.confirm("이 게시물을 삭제할까요? 댓글과 좋아요도 함께 삭제됩니다.")) deletePost(post.id); }}>삭제</button>}</header><span className={`community-category ${post.category ?? "discovery"}`}>{categoryLabel}</span>{post.speciesName && <div className="community-discovery"><DiscoveryImage label={post.speciesImageLabel ?? "◌"} tone={post.speciesImageTone ?? "upload"} name={post.speciesName} /><div><span className="eyebrow">DISCOVERY SHARE</span><b>{post.speciesName}</b><small>{post.locationName}</small></div></div>}<h2>{post.title}</h2><p>{post.content}</p><footer><button className={liked ? "liked" : ""} aria-pressed={liked} onClick={() => user && toggleLike(post.id)}>♥ 좋아요 {post.likes.length}</button><span>▢ 댓글 {post.comments.length}</span></footer><section className="community-comments">{post.comments.map((comment) => { const isMyComment = Boolean(visitorKey && comment.authorKey === visitorKey); return <div key={comment.id}><div className="comment-meta"><b>{comment.author}</b>{isMyComment && <button className="comment-delete" onClick={() => { if (window.confirm("이 댓글을 삭제할까요?")) deleteComment(post.id, comment.id); }}>삭제</button>}</div><p>{comment.content}</p><small>{new Date(comment.createdAt).toLocaleString("ko-KR")}</small></div>; })}<div className="comment-composer"><input aria-label={`${post.title} 댓글`} value={commentDrafts[post.id] ?? ""} onChange={(event) => setCommentDrafts((current) => ({ ...current, [post.id]: event.target.value }))} placeholder="응원 댓글을 남겨 보세요" maxLength={200} /><button onClick={() => sendComment(post.id)}>등록</button></div></section></article>; })}</section>}
  </section></AppShell></ProtectedPage>;
}
