"use client";
import { AppLink as Link } from "../../components/app-link";
import { useParams, useSearchParams } from "next/navigation";
import { AppShell } from "../../components/app-shell";
import { ProtectedPage } from "../../components/protected-page";
import { DiscoveryImage } from "../../components/discovery-image";
import { useDiscoveries } from "../../components/discovery-provider";
import { publicMapDiscoveries } from "../../data/map-data";
import { withBasePath } from "../../base-path";
export default function DiscoveryDetailClient() { const params = useParams<{ id: string }>(); const searchParams = useSearchParams(); const recordId = searchParams.get("id") ?? params.id; const { getDiscovery, isReady } = useDiscoveries(); const record = getDiscovery(recordId) ?? publicMapDiscoveries.find((item) => item.id === recordId); if (!isReady) return <div className="page-loading">기록을 불러오는 중…</div>; if (!record) return <ProtectedPage><AppShell><section className="not-found"><b>?</b><h1>발견 기록을 찾을 수 없어요</h1><Link className="primary-action" href="/collection">내 도감으로 이동</Link></section></AppShell></ProtectedPage>; return <ProtectedPage><AppShell><header className="form-heading"><p className="eyebrow">DISCOVERY DETAIL</p><h1>{record.speciesName} 발견 기록</h1></header><section className="record-detail"><DiscoveryImage label={record.imageLabel} tone={record.imageTone} name={record.speciesName} /><dl><div><dt>발견 장소</dt><dd>{record.locationName}</dd></div><div><dt>발견 일시</dt><dd>{new Date(record.discoveredAt).toLocaleString("ko-KR")}</dd></div><div><dt>크기</dt><dd>{record.size ? `${record.size}${record.sizeUnit}` : "기록 없음"}</dd></div><div><dt>환경</dt><dd>{record.environment} · {record.weather} · {record.tide}</dd></div><div><dt>AI 신뢰도</dt><dd>{record.aiConfidence}%</dd></div><div><dt>공개 여부</dt><dd>{record.visibility === "public" ? "공개" : "비공개"}</dd></div></dl>{record.memo && <blockquote>{record.memo}</blockquote>}<div className="complete-actions"><a className="primary-action" href={withBasePath(`/species/${record.speciesId}`)}>생물 상세 보기</a><a className="outline-action" href={withBasePath(`/map?discoveryId=${record.id}`)}>지도에서 보기</a></div></section></AppShell></ProtectedPage>; }
